### ISSUE TITLE
Look into options for specifying alternate email headers/footers

### ISSUE THREAD

**Issue by cjg89** [UCF/UCF-Email-Editor-Plugin#16]
**Description**

It'd be nice to be able to swap out individual email headers and/or footers quickly, either via existing Section selection (via ACF fields) or by setting up new sets of templates.  Currently the plugin only provides Leadership-specific layout options (the Tab header/footer with signature).

This may end up being an update to the GMUCF theme instead of this plugin, depending on how we decide to implement a solution.

**Why it's Important**

To assist in rapid development of email markup.

**Alternatives**

n/a

**Possible Implementation**

Either Section selection or new template options.  Or, something else I haven't thought of 🙂 

**Additional context**

**Comment by rjucf** [comment]
Added with #21
