### ISSUE TITLE
Sections inserted into some emails include <html> wrapper markup?

### ISSUE THREAD

**Issue by cjg89** [UCF/UCF-Email-Editor-Plugin#36]
**Describe the bug**

Some (but not all?) emails using the standard/"blank" template with header/sig/footer defined include doctype/html/body tags around the section markup.

**Steps to Reproduce**

View source on email listed in Slack

**Expected Behavior**

That wrapper markup should definitely not be there, and behavior should be consistent across all emails with this template.

**Possible Fix**

?

**Your environment:**

Checked in FF and Edge

**Additional context**

**Comment by jmbarne3** [comment]
Fixed by #37
