### ISSUE TITLE
Leadership template's title needs htmlentities processing

### ISSUE THREAD

**Issue by cjg89** [UCF/UCF-Email-Editor-Plugin#8]
**Describe the bug**

The htmlentities filtering we perform on email post content doesn't currently get applied to `the_title`, so email headings with special characters can potentially get garbled when sent.

https://github.com/UCF/UCF-Email-Editor-Plugin/blob/master/templates/leadership/leadership-template.php#L19

**Steps to Reproduce**

1. Create a new email with the leadership template and add a special character (such as a curly quotation mark) in the title of the post.
2. Export markup + send via Postmaster
3. Verify in email client

**Expected Behavior**

`the_title()` should output content safe for use within emails.

**Possible Fix**

Create a new function that only applies the character encoding adjustments to `the_title` hook.  (Can't use `convert_content_to_email_markup()`, since `the_content` and `the_title` expect a different number of arguments).

**Your environment:**

 - Browser & Version [e.g. chrome 68, safari]
 - WordPress Version: [e.g. 4.9.8]
 - Plugin Version: [e.g. 1.5.2]
n/a (most email clients)

**Additional context**

n/a

**Comment by rjucf** [comment]
Fixed in 1.1.1
